---
# Copyright (C) 2018-2020 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: Check if repository configuration is available
  check_mode: no
  stat:
    path: '{{ yum_repo_file }}'
  register: yum_repo_register_repofile

- name: Install repository package
  package:
    name: '{{ yum_repo_release_pkg }}'
    state: present
  when:
    - not yum_repo_register_repofile.stat.exists
    - yum_repo_release_pkg | length > 0

- name: Import repository GPG public key
  ignore_errors: '{{ ansible_check_mode }}'
  rpm_key:
    key: '{{ yum_repo_gpg_key }}'
    state: present
  when:
    - not yum_repo_register_repofile.stat.exists
    - yum_repo_gpg_key | length > 0

- name: Include tasks to configure repositories
  include_tasks: repo_config.yml
  loop: '{{ yum_repo_options.keys() | list }}'
  loop_control:
    loop_var: yum_repo_include_repo

- name: Include tasks to update repository metadata cache
  include_tasks: update_cache.yml
  when: yum_repo_update_cache | bool
