---

- name: Check if EPEL repo is already configured
  check_mode: no
  stat:
    path: '{{ epel_repo_file_path }}'
  register: epel_repo_register_repofile

- name: Install EPEL repository package
  package:
    name: '{{ epel_repo_url }}'
    state: present
  when: not epel_repo_register_repofile.stat.exists

- name: Import EPEL GPG key
  ignore_errors: '{{ ansible_check_mode }}'
  rpm_key:
    key: '{{ epel_repo_gpg_key_url }}'
    state: present
  when: not epel_repo_register_repofile.stat.exists

- name: Include tasks to configure repositories
  include_tasks: repo_config.yml
  loop: '{{ epel_repo_options.keys() | list }}'
  loop_control:
    loop_var: epel_repo_include_repo
