---

- name: '{{ yum_repo_include_repo }} - Set repository options'
  ignore_errors: '{{ ansible_check_mode }}'
  ini_file:
    path: '{{ yum_repo_file }}'
    section: '{{ yum_repo_include_repo }}'
    option: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
    no_extra_spaces: yes
  loop: '{{ yum_repo_options[yum_repo_include_repo] | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

# Avoid 'baseurl' and 'metalink' options being present
- name: '{{ yum_repo_include_repo }} - Cleanup metalink option'
  ignore_errors: '{{ ansible_check_mode }}'
  ini_file:
    path: '{{ yum_repo_file }}'
    section: '{{ yum_repo_include_repo }}'
    option: 'metalink'
    state: absent
    create: no
    no_extra_spaces: yes
  when: ('baseurl' in yum_repo_options[yum_repo_include_repo].keys())

- name: '{{ yum_repo_include_repo }} - Cleanup baseurl options'
  ignore_errors: '{{ ansible_check_mode }}'
  ini_file:
    path: '{{ yum_repo_file }}'
    section: '{{ yum_repo_include_repo }}'
    option: 'baseurl'
    state: absent
    create: no
    no_extra_spaces: yes
  when: ('metalink' in yum_repo_options[yum_repo_include_repo].keys())
