---

- name: '{{ yum_repo_include_repo }} - Set repository options'
  ignore_errors: '{{ ansible_check_mode }}'
  ini_file:
    path: '{{ yum_repo_file }}'
    section: '{{ yum_repo_include_repo }}'
    option: '{{ item.key }}'
    value: '{{ item.value }}'
    state: present
    no_extra_spaces: yes
  loop: '{{ yum_repo_options[yum_repo_include_repo] | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

#
# Avoid redundant options to be present if not explicitly defined
#

- name: '{{ yum_repo_include_repo }} - Cleanup redundant metalink option'
  ignore_errors: '{{ ansible_check_mode }}'
  ini_file:
    path: '{{ yum_repo_file }}'
    section: '{{ yum_repo_include_repo }}'
    option: 'metalink'
    state: absent
    create: no
  when:
    - ('baseurl' in yum_repo_options[yum_repo_include_repo].keys()) or
      ('mirrorlist' in yum_repo_options[yum_repo_include_repo].keys())
    - not 'metalink' in yum_repo_options[yum_repo_include_repo].keys()

- name: '{{ yum_repo_include_repo }} - Cleanup redundant mirrorlist option'
  ignore_errors: '{{ ansible_check_mode }}'
  ini_file:
    path: '{{ yum_repo_file }}'
    section: '{{ yum_repo_include_repo }}'
    option: 'mirrorlist'
    state: absent
    create: no
  when:
    - ('baseurl' in yum_repo_options[yum_repo_include_repo].keys()) or
      ('metalink' in yum_repo_options[yum_repo_include_repo].keys())
    - not 'mirrorlist' in yum_repo_options[yum_repo_include_repo].keys()

- name: '{{ yum_repo_include_repo }} - Cleanup redundant baseurl option'
  ignore_errors: '{{ ansible_check_mode }}'
  ini_file:
    path: '{{ yum_repo_file }}'
    section: '{{ yum_repo_include_repo }}'
    option: 'baseurl'
    state: absent
    create: no
  when:
    - ('metalink' in yum_repo_options[yum_repo_include_repo].keys()) or
      ('mirrorlist' in yum_repo_options[yum_repo_include_repo].keys())
    - not 'baseurl' in yum_repo_options[yum_repo_include_repo].keys()
