---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: Verify
  hosts: all

  tasks:
    - name: Check repository configuration file
      ansible.builtin.stat:
        path: '/etc/yum.repos.d/epel.repo'
      register: verify_register_repofile

    - name: Verify that repository configuration is available
      ansible.builtin.assert:
        quiet: true
        that: verify_register_repofile.stat.exists

    - name: List repositories
      changed_when: false
      ansible.builtin.command:
        argv:
          - '{{ "dnf" if ansible_distribution == "Fedora" else "yum" }}'
          - repolist
      register: verify_register_repolist

    - name: Verify that repository is in repolist
      ansible.builtin.assert:
        quiet: true
        that: '{% set _repo = [] %}{%
                  for _line in verify_register_repolist.stdout_lines %}{%
                    if (_line | regex_search("^epel")) %}{%
                      set _ = _repo.append(_line) %}{%
                    endif %}{%
                  endfor %}{{ _repo | length > 0 }}'
